---
  - name: Power off "{{ BMH_NODE }}"
    community.kubernetes.k8s:
      state: present
      definition:
        apiVersion: metal3.io/v1alpha1
        kind: BareMetalHost
        metadata:
          name: "{{ BMH_NODE }}"
          namespace: "{{ NAMESPACE }}"
          annotations:
            reboot.metal3.io/poweroff: ""

  - name: Wait until powered off "{{ K8S_NODE }}" becomes NotReady
    shell: "kubectl get nodes --kubeconfig {{ TARGET_KUBECONFIG }} | grep -w NotReady | awk '{print $1}' | sort"
    retries: 150
    delay: 3
    register: not_ready_nodes
    until: K8S_NODE in not_ready_nodes.stdout_lines

  - pause:
      minutes: 1

  - name: List only powered off VMs
    virt:
      command: list_vms
      state: shutdown
    register: shutdown_vms
    retries: 50
    delay: 10
    until: LIBVIRT_VM in shutdown_vms.list_vms
    become: yes
    become_user: root

  - name: Power on "{{ BMH_NODE }}"
    community.kubernetes.k8s:
      state: present
      definition:
        apiVersion: metal3.io/v1alpha1
        kind: BareMetalHost
        metadata:
          name: "{{ BMH_NODE }}"
          namespace: "{{ NAMESPACE }}"
          annotations:
            reboot.metal3.io/poweroff:

  - name: List only running VMs
    virt:
      command: list_vms
      state: running
    register: running_vms
    retries: 50
    delay: 10
    until: LIBVIRT_VM in running_vms.list_vms
    become: yes
    become_user: root

  - name: Wait until powered on "{{ K8S_NODE }}" becomes Ready
    shell: "kubectl get nodes --kubeconfig {{ TARGET_KUBECONFIG }} | grep -w Ready | awk '{print $1}' | sort"
    retries: 150
    delay: 3
    register: ready_nodes
    until: K8S_NODE in ready_nodes.stdout_lines